# Generated by Django 2.2 on 2020-10-20 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama')),
                ('lot_type', models.CharField(max_length=50, verbose_name='Tipe Rumah')),
                ('lot_length', models.FloatField(verbose_name='Panjang')),
                ('lot_width', models.FloatField(verbose_name='Lebar')),
                ('price', models.FloatField(verbose_name='Harga')),
            ],
        ),
        migrations.CreateModel(
            name='EstateGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Gambar')),
                ('description', models.CharField(max_length=100, verbose_name='Deskripsi')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Estate')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Alamat')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='No Telepon / HP')),
                ('fullname', models.CharField(max_length=100, verbose_name='Nama')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Akun')),
            ],
        ),
    ]
