# Generated by Django 2.2 on 2020-10-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='description',
            field=models.TextField(default='', verbose_name='Deskripsi'),
        ),
        migrations.AddField(
            model_name='estate',
            name='locations',
            field=models.TextField(default='', verbose_name='Lokasi'),
        ),
        migrations.AddField(
            model_name='estategallery',
            name='image_type',
            field=models.CharField(choices=[('cover', 'Gambar Cover'), ('gallery', 'Galeri')], default='', max_length=50),
        ),
        migrations.CreateModel(
            name='EstateDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_payment', models.FloatField(blank=True, default=0.0, null=True)),
                ('installment', models.IntegerField(blank=True, default=0, null=True)),
                ('installment_pay', models.FloatField(blank=True, default=0.0, null=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Estate')),
            ],
        ),
    ]
